name = "My Awesome Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f1a6bc2f29ffee6646f3d5acbbf9803566b992f5a7929ed0e874b47a40d74d1"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
