name = "My Awesome Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96422129edcead6b4507ad8382f3e7ddef48eccd1dc7918fb95dacf0aadae77b"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
