name = "My Awesome Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a63e79ae838ff7c62a9a948f1e211174b3b39c0d5743f44161f5d6c326a13f7a"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
